### ISSUE TITLE
Wrapping assisticantfacades in a Windows Runtime Component

### ISSUE THREAD

**Issue by alfred-png** [robertvazan/assisticantfacades#1]
Hi Robert,
great work! Thank you!
I do a new project and want to use WinUI 3.0 with C++/WinRT for desktop applications. I think about using assisticantFacades instead of the x:Bind markup extensions. But therefore I need to wrap assisticantFacades in a Windows Runtime Component to be able to use it? Is that possible? I'm not so familiar with that task. 
Or do you consider providing such a port of your own?
Cheers
Alfred

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
